#!/usr/bin/env python

from pygit2 import Repository, Signature, GIT_FILEMODE_TREE, GIT_FILEMODE_BLOB
import os


def build_tree(repo, dir_path):
    tree_builder = repo.TreeBuilder()
    for _f in os.listdir(dir_path):
        f = os.path.join(dir_path, _f)
        if os.path.isdir(f):
            tree_builder.insert(_f, build_tree(repo, f), GIT_FILEMODE_TREE)
        elif os.path.isfile(f):
            with open(f, 'rb') as fp:
                tree_builder.insert(_f, repo.create_blob(fp.read()),
                                    GIT_FILEMODE_BLOB)
        elif os.path.islink(f):  # TODO: support symlinks
            pass
    return tree_builder.write()


def create_commit(repository_path, input_path, branch_name, commit_message,
                  cname=None, jekill=False):
    repo = Repository(repository_path)
    tree_oid = build_tree(repo, input_path)
    tree_builder = repo.TreeBuilder(tree_oid)
    if cname is not None:
        tree_builder.insert('CNAME', repo.create_blob('%s\n' % cname),
                            GIT_FILEMODE_BLOB)
    if not jekill:
        tree_builder.insert('.nojekill', repo.create_blob(''),
                            GIT_FILEMODE_BLOB)
    tree_oid = tree_builder.write()
    author = Signature(repo.config['user.name'], repo.config['user.email'])
    branch_full_name = 'refs/heads/%s' % branch_name
    try:
        branch_ref = repo.lookup_reference(branch_full_name)
    except KeyError:
        parents = []
    else:
        parents = [branch_ref.target]
    commit = repo.create_commit(branch_full_name, author, author,
                                commit_message, tree_oid, parents)
